# Generated by Django 3.2.5 on 2023-05-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='is_non_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='primary_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
