# Generated by Django 3.2.5 on 2023-05-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0004_auto_20230502_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='scheme_type',
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_non_individual',
            field=models.BooleanField(default=False),
        ),
    ]
