# Generated by Django 3.2.5 on 2023-05-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0007_alter_caste_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheme.department'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheme.ministry'),
        ),
    ]
