# Generated by Django 3.2.5 on 2023-05-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0008_auto_20230502_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
